/**
 * @nockchain/rose-ts — pure TypeScript drop-in for protocol-facing rose-wasm APIs.
 */

export {DEFAULT_FEE_PER_WORD} from './constants.js';
export {NotImplementedError} from './stubs.js';

export type {
  Digest,
  PbCom2RawTransaction,
  Hax,
  Lock,
  LockPrimitive,
  LockRoot,
  LockTim,
  MissingUnlocks,
  Name,
  Nicks,
  NockchainTx,
  Note,
  NoteData,
  NoteV1,
  Pkh,
  RawTxV1,
  SeedV1,
  Signature,
  Source,
  SpendCondition,
  TxEngineSettings,
  TxLock,
  Witness,
} from './types.js';

export type {Balance, BalanceEntry} from './rpc/types.js';
export type {GrpcBlocks, GrpcBlockEntry} from './rpc/client.js';
export type {OutputNoteData} from './tx/types.js';
export type {SimpleSpendLockOptions} from './tx/builder.js';

export {
  jam,
  cue,
  tas,
  untas,
  tasBelts,
  atomToBelts,
  beltsToAtom,
} from './noun/index.js';
export {
  deriveMasterKey,
  deriveMasterKeyFromMnemonic,
  ExtendedKey,
  hashPublicKey,
  PrivateKey,
  PublicKey,
  publicKeyFromBeBytes,
  publicKeyFromHex,
  publicKeyToHex,
  publicKeyVerify,
  signMessage,
  verifySignature,
} from './crypto/index.js';
export {
  hashPreimage,
  hashNoun,
  hashStructuredNoun,
  hashU64,
  pkhSingle,
  pkhNew,
  pkhHash,
  haxHash,
  haxHashPreimage,
  spendConditionNewPkh,
  spendConditionPkh,
  spendConditionHax,
  spendConditionTim,
  spendConditionBrn,
  spendConditionFirstName,
  spendConditionHash,
  lockFromList,
  lockFromListBurnpad,
  lockRootHash,
  lockHash,
  lockHeight,
  lockProve,
  noteDataEmpty,
  noteDataPushPkh,
  noteDataPushLock,
  noteDataPushMemo,
  noteDataPushBlob,
  decodeNoteDataPackedUtf8,
  decodePackedBlobUtf8,
  noteHash,
  nameV1,
  nameHash,
  hashName,
  hashSeedV1Digest,
  hashSeedsV1Digest,
  hashSpendV1SigHash,
  hashWitnessDigest,
  hashPkhSignatureDigest,
  hashSpendsV1,
  hashLockMerkleProofDigest,
  seedV1NewSinglePkh,
} from './hash/index.js';
export {
  TxBuilder,
  SpendBuilder,
  txEngineSettingsV1Default,
  txEngineSettingsV1BythosDefault,
  nockchainTxToRawTx,
  rawTxV1ToNockchainTx,
  rawTxV1New,
  rawTxV1Version,
  rawTxV1InputNames,
  rawTxV1InputSpendConditions,
  spendV1NewWitness,
  spendV1NewLegacy,
  spendV1SigHash,
  nockchainTxOutputs,
  rawTxV1Outputs,
  rawTxTotalFees,
  rawTxV1CalcId,
  spendV1Fee,
  spendV1TotalGifts,
  spendV1UnclampedFee,
  spendsV1Fee,
  spendsV1TotalFees,
  spendsV1TotalGifts,
  spendsV1UnclampedFee,
  spendsV1ApplyWitness,
  witnessFromLock,
  witnessNew,
  lockMerkleProofFromLock,
  witnessFromLockMerkleProof,
  witnessClearSignatures,
  witnessWithPkhSignature,
  witnessWithHaxPreimage,
  spendV1FromLock,
  multisigLock,
  giftOutputFirstNameFromLockOutputs,
  htlcGiftOutputFirstName,
  htlcOrLock,
  htlcLockRootDigest,
} from './tx/index.js';
export {RpcClient} from './rpc/client.js';

/** @deprecated Use RpcClient — protobuf naming is wire-internal. */
export {GrpcClient} from './grpc/index.js';
/** @deprecated Wire-internal; use domain types + RpcClient.sendTransaction. */
export {
  noteFromProtobuf,
  noteToProtobuf,
  spendConditionFromProtobuf,
  spendConditionToProtobuf,
  digestFromProtobuf,
  digestToProtobuf,
  rawTxFromProtobuf,
  rawTxToProtobuf,
} from './proto/index.js';
